### ISSUE TITLE
:troll: https://github.com/master7720/Minecraft-Deobfuscator3000.jar-src

### ISSUE THREAD

**Issue by master7720** [SimplyProgrammer/Minecraft-Deobfuscator3000#5]
dm me if you want me to deleted the repo

**Comment by Aholicknight** [comment]
what is this lmao

**Comment by Kiffolisk** [comment]
wow good job youdecompiled a jar

**Comment by Aholicknight** [comment]
> wow good job youdecompiled a jar

ikr literally anyone can do this lmao
